name: qa4sm_reader
channels:
- defaults
- conda-forge
dependencies:
- python=3.10
- xarray
- netcdf4
- pandas
- numpy
- matplotlib
- cartopy>=0.21
- pyproj
- h5netcdf
- pip
- pip:
    - parse
    - colorcet
    - scipy
    - seaborn
    - pygeogrids
    - pytest
    - pytest-cov
