name: qa4sm_reader
channels:
- defaults
- conda-forge
dependencies:
- xarray>=2024.11.0
- netcdf4
- pandas
- numpy
- matplotlib
- cartopy>=0.21
- pyproj
- h5netcdf
- pip
- pip:
    - cftime>=1.6.4
    - parse
    - colorcet
    - scipy
    - seaborn
    - pygeogrids
    - pytest
    - pytest-cov
    - pytesmo
